---
- hosts: all
  become: true
  vars:
    crontab_prune_enable: "${CRONTAB_PRUNE_ENABLE}"
    crontab_prune_command: "${CRONTAB_PRUNE_COMMAND}"

    docker_group_enable: "${DOCKER_GROUP_ENABLE}"
    docker_group_user: "${DOCKER_GROUP_USER}"

    default_container_enable: "${DEFAULT_CONTAINER_ENABLE}"
    default_container_name: "${DEFAULT_CONTAINER_NAME}"
    default_container_image: "${DEFAULT_CONTAINER_IMAGE}"

  tasks:
    # do initial configuration of the packages
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
    - name: Install required src packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools' ]

    # configure the docker repository
    - name: Add docker gpg apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    # install docker with dependencies
    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
    - name: Install docker module for python
      pip:
        name: docker

    # configure the crontab to automatically clean docker environment
    - name: Add crontab command to prune docker all unassociated data
      when: crontab_prune_enable|bool == True
      cron:
        name: "docker system prune"
        minute: "0"
        hour: "1"
        job: "{{ crontab_prune_command }} > /dev/null"

    # include user into the docker group
    - name: Ensure group "docker" exists
      when: docker_group_enable|bool == True
      group:
        name: docker
        state: present
    - name: Adding user "{{ docker_group_user }}" to the docker group
      when: docker_group_enable|bool == True
      user:
        name: "{{ docker_group_user }}"
        groups: docker
        append: yes

    # setup default docker image
    - name: Pull default docker image
      when: default_container_enable|bool == True
      docker_image:
        name: "{{ default_container_image }}"
        source: pull
    - name: Create default container
      when: default_container_enable|bool == True
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        state: started
        ports:
          - "8001:80"
